name: Build

on:
  push:
    branches:
      - 'deno'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    steps:
      - uses: actions/checkout@v3
      - name: Install xsel on ubuntu
        if: ${{matrix.os == 'ubuntu-22.04'}}
        run: |
          sudo apt-get install xsel
      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x 
      - run: | 
          deno test --allow-run --allow-all test/

