name: Tests

on:
  push:
    branches:
      - '*'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install xsel
      run: xvfb-run npm t
    - name: Install modules
      run: yarn
    - name: Install latest rgc
      run: npm i -g .
    - name: Run tests
      run: yarn test