name: Tests

on:
  push:
    branches:
      - '*'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Install latest rgc
      run: npm i -g .
    - name: Run tests prompt.test.ts
      run: npx jest prompt.test.ts
    - name: Run tests bigSmallLetter.test.ts
      run: npx jest bigSmallLetter.test.ts
    - name: Run tests useStateGen.test
      run: npx jest useStateGen.test